slam_toolbox:
  ros_parameters:

  #Plugin params
  solver_plugin: solver_plugins::CeresSolver
  ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
  ceres_preconditioner: SCHUR_JACOBI
  ceres_trust_strategy: LEVENBERG_MARQUARDT
  ceres_dogleg_type: TRADITIONAL_DOGLEG
  ceres_loss_function: None

  odom_frame: odom
  map_frame: map
  base_frame: base_footprint
  scan_topic: /scan
  mode: mapping


  debug_logging: false
  throttle_scans: 1
  transform_publish_period: 0.02
  map_update_interval: 5.0
  resolution: 0.05
  max_laser_range: 20.0
  minimum_time_interval: 0.5
  transform_timeout: 0.2
  tf_buffer_duration: 30.
  stack_size_to_use: 40000000
  enable_interactive_mode: true
  

  use_scan_matching: true
  use_scan_barycenter: true
  min